sudo: required
language: java
dist: trusty

jdk:
  - oraclejdk8
 
before_install:
  - git config --global user.email "travis-ci@travis-ci.org"
  - git config --global user.name "Travis CI"
 
before_script:
  - chmod +x scripts/inst.sh
script: ./scripts/inst.sh --setup --remote

cache:
  directories:
    - '$HOME/.m2/repository'
    - 'work/Paper/work/Minecraft'
